/**
 * QARAH — Pet Name Database
 * 인상 유형별 반려동물 이름 (구분 없이 공용)
 */
export const petNames = {
    female: {
        water: [
            { name: '물방울', meaning: '맑은 눈의 조용한 파트너'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '이슬', meaning: '아침 이슬처럼 깨끗한 아이'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
            { name: '미스티', meaning: '안개처럼 신비로운 친구 (Misty)'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '코랄', meaning: '산호처럼 아름다운 아이 (Coral)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
            { name: '아쿠아', meaning: '물처럼 맑은 눈의 친구 (Aqua)'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '브룩', meaning: '시냇물처럼 졸졸 흐르는 아이 (Brooke)'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
            { name: '마리나', meaning: '바다를 좋아하는 친구 (Marina)'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '펄', meaning: '진주처럼 귀한 아이 (Pearl)'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
            { name: '씨', meaning: '바다처럼 넓은 마음의 친구 (Sea)'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '크리스탈', meaning: '수정처럼 맑은 아이 (Crystal)'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
        ],
        fire: [
            { name: '불꽃이', meaning: '에너지가 넘치는 활발한 아이'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '레드', meaning: '빨간 에너지의 장난꾸러기 (Red)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
            { name: '스파크', meaning: '불꽃처럼 튀는 아이 (Spark)'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '피닉스', meaning: '불사조처럼 강한 친구 (Phoenix)'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
            { name: '블레이즈', meaning: '불길처럼 뜨거운 아이 (Blaze)'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '루비', meaning: '루비처럼 빨갛고 귀한 친구 (Ruby)'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
            { name: '타이거', meaning: '호랑이처럼 용맹한 아이 (Tiger)'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '치타', meaning: '치타처럼 빠른 친구 (Cheetah)'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
            { name: '볼케이노', meaning: '화산처럼 에너지 넘치는 아이'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '페퍼', meaning: '후추처럼 짜릿한 친구 (Pepper)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
        ],
        forest: [
            { name: '나무', meaning: '숲에서 온 듯한 편안한 친구'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '올리브', meaning: '평화로운 성격의 아이 (Olive)'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
            { name: '미도리', meaning: '초록빛처럼 편안한 친구'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '버디', meaning: '가장 좋은 친구 (Buddy)'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
            { name: '모스', meaning: '이끼처럼 포근한 아이 (Moss)'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '허니', meaning: '꿀처럼 달콤한 친구 (Honey)'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
            { name: '클로버', meaning: '행운의 네잎클로버 (Clover)'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '피넛', meaning: '땅콩처럼 작고 귀여운 친구 (Peanut)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
            { name: '코코', meaning: '코코넛처럼 달콤한 아이 (Coco)'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '단풍이', meaning: '가을 단풍처럼 아름다운 친구'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
        ],
        star: [
            { name: '별이', meaning: '밤하늘 별처럼 빛나는 아이'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '스텔라', meaning: '별처럼 빛나는 친구 (Stella)'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
            { name: '반짝이', meaning: '반짝반짝 빛나는 귀여운 아이'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '루나', meaning: '달빛처럼 아름다운 친구 (Luna)'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
            { name: '노바', meaning: '신성처럼 빛나는 아이 (Nova)'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '마블', meaning: '대리석처럼 고급스러운 친구 (Marble)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
            { name: '다이아', meaning: '다이아몬드처럼 빛나는 아이'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '오로라', meaning: '오로라처럼 신비로운 친구 (Aurora)'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
            { name: '티아라', meaning: '왕관처럼 고귀한 아이 (Tiara)'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '프리즘', meaning: '무지개 빛의 친구 (Prism)'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
        ],
        rock: [
            { name: '바위', meaning: '듬직하고 든든한 친구'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '록키', meaning: '바위처럼 강한 아이 (Rocky)'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
            { name: '탱크', meaning: '튼튼한 체격의 든든한 친구 (Tank)'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '캡틴', meaning: '대장 기질의 리더 친구 (Captain)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
            { name: '킹', meaning: '왕처럼 위엄 있는 아이 (King)'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '아이언', meaning: '철처럼 강한 친구 (Iron)'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
            { name: '브루투스', meaning: '강인한 수호자 (Brutus)'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '타이탄', meaning: '거대한 존재감의 아이 (Titan)'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
            { name: '볼트', meaning: '번개처럼 빠르고 강한 친구 (Bolt)'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '렉스', meaning: '왕처럼 당당한 아이 (Rex)'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
        ],
        flower: [
            { name: '꽃이', meaning: '꽃처럼 예쁜 사랑스런 친구'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '로즈', meaning: '장미처럼 아름다운 아이 (Rose)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
            { name: '데이지', meaning: '데이지처럼 밝은 친구 (Daisy)'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '릴리', meaning: '백합처럼 순수한 아이 (Lily)'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
            { name: '봄이', meaning: '봄처럼 화사한 친구'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '재스민', meaning: '재스민향처럼 향기로운 아이 (Jasmine)'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
            { name: '바이올렛', meaning: '보라꽃처럼 우아한 친구 (Violet)'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '사쿠라', meaning: '벚꽃처럼 아름다운 아이 (Sakura)'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
            { name: '포피', meaning: '양귀비처럼 화사한 친구 (Poppy)'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '카멜리아', meaning: '동백처럼 고귀한 아이 (Camellia)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
        ],
        moon: [
            { name: '달이', meaning: '달빛처럼 은은한 친구'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '미스터리', meaning: '신비로운 매력의 아이 (Mystery)'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
            { name: '섀도우', meaning: '그림자처럼 조용한 친구 (Shadow)'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '밤이', meaning: '밤처럼 조용하고 깊은 아이'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
            { name: '미드나잇', meaning: '한밤중의 신비로운 친구 (Midnight)'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '오닉스', meaning: '흑요석처럼 깊은 아이 (Onyx)'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
            { name: '벨벳', meaning: '벨벳처럼 부드러운 친구 (Velvet)'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '살렘', meaning: '신비로운 밤의 친구 (Salem)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
            { name: '네뷸라', meaning: '성운처럼 신비한 아이 (Nebula)'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '위스퍼', meaning: '속삭이듯 조용한 친구 (Whisper)'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
        ],
        sun: [
            { name: '해피', meaning: '행복을 주는 밝은 친구 (Happy)'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '츄', meaning: '뽀뽀 좋아하는 사랑둥이'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
            { name: '써니', meaning: '햇살처럼 밝은 아이 (Sunny)'  , emotionAffinity: { joy: 0.9, calm: 0.9, mystery: 0.5, passion: 0.9, soulful: 0.5, bold: 0.9 } },
            { name: '골디', meaning: '금빛처럼 빛나는 친구 (Goldie)'  , emotionAffinity: { joy: 0.6, calm: 1, mystery: 0.4, passion: 0.6, soulful: 0.4, bold: 0.6 } },
            { name: '망고', meaning: '달콤한 과일 같은 아이 (Mango)'  , emotionAffinity: { joy: 0.3, calm: 0.3, mystery: 0.3, passion: 0.3, soulful: 0.3, bold: 0.3 } },
            { name: '선샤인', meaning: '햇살처럼 따뜻한 친구 (Sunshine)'  , emotionAffinity: { joy: 0.8, calm: 0.4, mystery: 1, passion: 0.8, soulful: 1, bold: 0.8 } },
            { name: '또또', meaning: '또 보고 싶은 귀여운 아이'  , emotionAffinity: { joy: 0.5, calm: 0.5, mystery: 0.9, passion: 0.5, soulful: 0.9, bold: 0.5 } },
            { name: '레몬', meaning: '상큼한 매력의 친구 (Lemon)'  , emotionAffinity: { joy: 1, calm: 0.6, mystery: 0.8, passion: 1, soulful: 0.8, bold: 1 } },
            { name: '치즈', meaning: '치즈처럼 노란 귀여운 아이'  , emotionAffinity: { joy: 0.7, calm: 0.7, mystery: 0.7, passion: 0.7, soulful: 0.7, bold: 0.7 } },
            { name: '쿠키', meaning: '달콤한 쿠키 같은 친구 (Cookie)'  , emotionAffinity: { joy: 0.4, calm: 0.8, mystery: 0.6, passion: 0.4, soulful: 0.6, bold: 0.4 } },
        ]
    },
    male: null // male 데이터는 female과 동일하게 사용 (반려동물은 성별 구분 없음)
};

// 반려동물은 성별 구분 없이 female 데이터를 공용으로 사용
petNames.male = petNames.female;
